import Head from 'next/head'
import styles from '../styles/home/Home.module.scss'
import { useState } from 'react'
import { useRouter } from 'next/router'

//data
import formatDate from '../utility/formatDate'
import formatNumber from '../utility/formatNumber'

//components
import Loader from '../components/loader'
import Footer from '../components/footer'

const Home =()=> {

  let [isLoading, setLoading] = useState(false)

  let router = useRouter()
  let ticketData = require('../data/ticket.json')

  const WebPage =()=> {

    const SelectSection =()=>{

      return(
        <>
          <section className={styles.content}>
            <div className={styles.titleHeader}>
                <h1>Tickets List</h1>
            </div>
            <div className={styles.listTicket}>
              {
                ticketData.map((item,key) => {
                  return(
                  <div key={key} className={styles.ticketBox}>
                    <div className={styles.title}>
                      <h2>{item.ticket_name}</h2>
                      <p>( {item.ticket_type} )</p>
                    </div>
                    <div className={styles.content}>
                      <p>Location: {item.ticket_location}</p>
                      <p>Venue capacity: {formatNumber(item.ticket_vanue_capacity)}</p>
                      <p>Date: {formatDate(item.ticket_date)}</p>
                      <p>Price: {formatNumber(item.ticket_price)} $</p>
                    </div>
                    <div className={styles.input}>
                      <p>{formatNumber(item.ticket_amount)} tickets remaining</p>
                      <div className={styles.select} 
                          onClick={()=> { router.push({pathname: '/checkout', query: {ticket_id: item.ticket_id}}) }
                      }>
                        Buy this ticket
                      </div>
                    </div>
                  </div>
                  )
                })
              }
            </div>
          </section>
        </>
      )
    }

    return (
      <>
        <section className={styles.webPage}>
          <SelectSection />
        </section>
        <Footer />
      </>
    )
  }

  return (
    <>
      <Head>
        <title>Ticket Purchasing UI</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {(isLoading === true) ? <Loader />:<WebPage />}
    </>
  )
}

export default Home